# title: Netec Learning Labs
description: Plataforma de Laboratorios · Introducción a Docker y Kubernetes

# Para project site:
url: "https://netec-mx.github.io" # CAMBIAR LA CUENTA
baseurl: "/DOCK_KUB_V2"   # CLAVE para que no se rompan rutas siempre cambiar

# Para local Recuerda ajustar rutas en los archivos
# url: "http://localhost:4000"
# baseurl: ""

# Si usas un tema remoto (opcional):
# remote_theme: owner/tema

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .bundle
  - vendor
  - node_modules
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md

logo: /assets/img/neteclogo.png
favicon: /assets/img/favicon.ico